homeRegion: &HOME_REGION us-east-1
disasterRecoveryRegion: &DR_REGION us-west-2
enabledRegions:
  - *HOME_REGION
  - *DR_REGION
managementAccountAccessRole: AWSControlTowerExecution
cloudwatchLogRetentionInDays: 180
snsTopics:
  deploymentTargets:
    organizationalUnits:
      - Root
  topics:
    - emailAddresses:
        - notify@example.com
      name: Security
cdkOptions:
  centralizeBuckets: true
  useManagementAccessRole: true
terminationProtection: true
controlTower:
  enable: true
  landingZone:
    version: '3.3'
    logging:
      loggingBucketRetentionDays: 1095
      accessLoggingBucketRetentionDays: 1095
      organizationTrail: true
    security:
      enableIdentityCenterAccess: true
  controls: []
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
    organizationTrailSettings:
      multiRegionTrail: true
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: true
      lambdaDataEvents: true
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
    accountTrails: []
    lifecycleRules: []
  sessionManager:
    sendToCloudWatchLogs: false
    sendToS3: true
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 730
        noncurrentVersionExpiration: 730
    attachPolicyToIamRoles:
      - EC2-Default-SSM-AD-Role
  cloudwatchLogs:
    encryption:
      useCMK: true
      deploymentTargets:
        accounts:
          - Management
        organizationalUnits:
          - Security
          - Infrastructure
          - Deploy
          - Sandbox
          - inv/Workloads/Non-Prod/Dev
          - inv/Workloads/Non-Prod/Test
          - inv/Workloads/Prod/Stage
          - inv/Workloads/Prod/Prod-Int
          - inv/Workloads/Prod/Prod-Ext
    enable: true
    dynamicPartitioning: dynamic-partitioning/log-filters.json
    replaceLogDestinationArn: replaceLogDestinationArn
    exclusions:
      # - organizationalUnits:
      #     - Infrastructure
      #   excludeAll: true
      - organizationalUnits:
          - Root
        logGroupNames:
          - test1/*
      - accounts:
          - Management
        logGroupNames:
          - test/*
  accessLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 1095
        noncurrentVersionExpiration: 1095
        transitions:
          - storageClass: GLACIER_IR
            transitionAfter: 180
        noncurrentVersionTransitions:
          - storageClass: GLACIER_IR
            transitionAfter: 180
  centralLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 1095
        noncurrentVersionExpiration: 1095
        transitions:
          - storageClass: GLACIER_IR
            transitionAfter: 180
        noncurrentVersionTransitions:
          - storageClass: GLACIER_IR
            transitionAfter: 180
    s3ResourcePolicyAttachments:
     - policy: bucket-policies/central-log-bucket.json
  elbLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 1095
        noncurrentVersionExpiration: 1095
        transitions:
          - storageClass: GLACIER_IR
            transitionAfter: 180
        noncurrentVersionTransitions:
          - storageClass: GLACIER_IR
            transitionAfter: 180         
reports:
  budgets:
    - deploymentTargets:
        accounts:
          - sandbox-learn01
      name: inv-sanbdox-acct-budget-notification
      timeUnit: MONTHLY
      type: COST
      amount: 1000
      includeUpfront: true
      includeTax: true
      includeSupport: true
      includeSubscription: true
      includeRecurring: true
      includeOtherSubscription: true
      includeDiscount: true
      includeCredit: false
      includeRefund: false
      useBlended: false
      useAmortized: false
      unit: USD
      notifications:
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 100
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          recipients: 
           - test@test.com
tags: 
  - key: division
    value: test
  - key: app
    value: inv-lza
iamRoleSsmParameters: []
