AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy AWS WAFv2 using Firewall Manager with WAF rules applied to CloudFront across multiple accounts and organizational units

Parameters:
  pBlockedIp:
    Description: The IP address to block
    Type: CommaDelimitedList
    Default: '1.2.1.1/32'
  pMemberAccounts:
    Description: The list of account IDs to apply the policy to (comma-separated) for sandbox
    Type: CommaDelimitedList
    Default: 'xxxx'
  pOrganizationOUIdNP:
    Description: The ID of the Organizational Unit to apply the policy to Non Production OUS
    Type: CommaDelimitedList
    Default: 'xxx'
  pExceptionTagKey:
    Description: The key for the tag that will exclude CloudFront distributions from WAF
    Type: String
  pExceptionTagValue:
    Description: The value for the tag that will exclude CloudFront distributions from WAF
    Type: String

Resources:

  rBlockedIpSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: BlockedIpSet
      Scope: CLOUDFRONT
      IPAddressVersion: IPV4
      Addresses: !Ref pBlockedIp
  # rWebACL:
  #   Type: AWS::WAFv2::WebACL
  #   Properties:
  #     Name: CloudFrontWebACL
  #     Scope: CLOUDFRONT
  #     DefaultAction:
  #       Allow: {}
  #     VisibilityConfig:
  #       SampledRequestsEnabled: true
  #       CloudWatchMetricsEnabled: true
  #       MetricName: CloudFrontWebACL
  #     Rules:
  #       # - Name: AWSManagedRulesAmazonIpReputationList
  #       #   Priority: 0
  #       #   Statement:
  #       #     ManagedRuleGroupStatement:
  #       #       VendorName: AWS
  #       #       Name: AWSManagedRulesAmazonIpReputationList
  #       #   OverrideAction:
  #       #     None: {}
  #       #   VisibilityConfig:
  #       #     SampledRequestsEnabled: true
  #       #     CloudWatchMetricsEnabled: true
  #       #     MetricName: AWSManagedRulesAmazonIpReputationList
  #       # - Name: AWSManagedRulesCommonRuleSet
  #       #   Priority: 1
  #       #   Statement:
  #       #     ManagedRuleGroupStatement:
  #       #       VendorName: AWS
  #       #       Name: AWSManagedRulesCommonRuleSet
  #       #   OverrideAction:
  #       #     None: {}
  #       #   VisibilityConfig:
  #       #     SampledRequestsEnabled: true
  #       #     CloudWatchMetricsEnabled: true
  #       #     MetricName: AWSManagedRulesCommonRuleSet
  #       # - Name: AWSManagedRulesKnownBadInputsRuleSet
  #       #   Priority: 2
  #       #   Statement:
  #       #     ManagedRuleGroupStatement:
  #       #       VendorName: AWS
  #       #       Name: AWSManagedRulesKnownBadInputsRuleSet
  #       #   OverrideAction:
  #       #     None: {}
  #       #   VisibilityConfig:
  #       #     SampledRequestsEnabled: true
  #       #     CloudWatchMetricsEnabled: true
  #       #     MetricName: AWSManagedRulesKnownBadInputsRuleSet
  #       - Name: CustomBlockRule
  #         Priority: 0
  #         Statement:
  #           IPSetReferenceStatement:
  #             Arn: !GetAtt rBlockedIpSet.Arn
  #         Action:
  #           Block: {}
  #         VisibilityConfig:
  #           SampledRequestsEnabled: true
  #           CloudWatchMetricsEnabled: true
  #           MetricName: CustomBlockRule
  rCustomRuleIpGroup:
    Type: AWS::WAFv2::RuleGroup
    Properties:
      Capacity: 100
      Name: CustomRuleIpGroup
      Scope: CLOUDFRONT
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: CustomRuleIPGroup
      Rules:
        - Name: CustomBlockIpRule
          Priority: 0
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt rBlockedIpSet.Arn
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CustomBlockIpRule

  rFirewallManagerPolicyNonProd:
    Type: AWS::FMS::Policy
    Properties:
      PolicyName: CloudFrontWebACLPolicy
      RemediationEnabled: true
      ExcludeResourceTags: true
      ResourceTags:
        - Key: !Ref pExceptionTagKey
          Value: !Ref pExceptionTagValue
      IncludeMap:
        ACCOUNT: !Ref pMemberAccounts
        ORGUNIT: !Ref pOrganizationOUIdNP
      ResourceType: AWS::CloudFront::Distribution
      SecurityServicePolicyData:
        Type: WAFV2
        ManagedServiceData: !Sub '{"type":"WAFV2", 
                                  "preProcessRuleGroups":[{ 
                                  "ruleGroupType":"RuleGroup",
                                  "ruleGroupArn":"${rCustomRuleIpGroup.Arn}",
                                  "overrideAction":{"type":"NONE"}},{
                                  "managedRuleGroupIdentifier":{
                                  "managedRuleGroupName":"AWSManagedRulesAmazonIpReputationList", 
                                  "vendorName":"AWS"},
                                  "overrideAction":{"type":"NONE"}, 
                                  "excludeRules":[],"ruleGroupType":"ManagedRuleGroup"},{
                                  "managedRuleGroupIdentifier":{
                                  "managedRuleGroupName":"AWSManagedRulesCommonRuleSet", 
                                  "vendorName":"AWS"},
                                  "overrideAction":{"type":"COUNT"}, 
                                  "excludeRules":[],"ruleGroupType":"ManagedRuleGroup"},{
                                  "managedRuleGroupIdentifier":{
                                  "managedRuleGroupName":"AWSManagedRulesKnownBadInputsRuleSet", 
                                  "vendorName":"AWS"},
                                  "overrideAction":{"type":"NONE"}, 
                                  "excludeRules":[],"ruleGroupType":"ManagedRuleGroup"}],
                                  "postProcessRuleGroups":[],
                                  "defaultAction":{"type":"ALLOW"}}'
Outputs:
  # oWebACLArn:
  #   Description: The ARN of the created WebACL
  #   Value: !GetAtt rWebACL.Arn
  oFirewallManagerPolicyIdNP:
    Description: The ID of the created Firewall Manager policy
    Value: !Ref rFirewallManagerPolicyNonProd
